# Generated by Django 5.1 on 2024-09-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffattendance_aproved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='aproved_by',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
