# Generated by Django 5.1 on 2024-09-21 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('intake_capacity', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('year', models.CharField(choices=[('1st year', '1st year'), ('2nd year', '2nd year'), ('Direct second year', 'Direct second year'), ('3rd year', '3rd year'), ('4th year', '4th year')], max_length=20)),
                ('semester', models.CharField(choices=[('1 semester', '1 semester'), ('2 semester', '2 semester'), ('3 semester', '3 semester'), ('4 semester', '4 semester'), ('5 semester', '5 semester'), ('6 semester', '6 semester'), ('7 semester', '7 semester'), ('8 semester', '8 semester')], max_length=20)),
                ('division', models.CharField(max_length=100)),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institutemaster')),
            ],
        ),
    ]
