# Generated by Django 5.1 on 2024-09-21 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemaster',
            name='division',
        ),
        migrations.RemoveField(
            model_name='coursemaster',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='coursemaster',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='coursemaster',
            name='year',
        ),
        migrations.CreateModel(
            name='DivisionMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(choices=[('1st year', '1st year'), ('2nd year', '2nd year'), ('Direct second year', 'Direct second year'), ('3rd year', '3rd year'), ('4th year', '4th year')], max_length=20)),
                ('semester', models.CharField(choices=[('1 semester', '1 semester'), ('2 semester', '2 semester'), ('3 semester', '3 semester'), ('4 semester', '4 semester'), ('5 semester', '5 semester'), ('6 semester', '6 semester'), ('7 semester', '7 semester'), ('8 semester', '8 semester')], max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemaster')),
            ],
        ),
    ]
