# Generated by Django 5.1 on 2024-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_coursemaster_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemaster',
            name='durstion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
