# Generated by Django 5.1 on 2024-09-21 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('both', 'Both')], max_length=20)),
                ('marks_credits', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('pattern', models.CharField(max_length=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemaster')),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusMaster',
            fields=[
                ('syllabus_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=255)),
                ('points_sub_points', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subjectmaster')),
            ],
        ),
    ]
