# Generated by Django 5.1 on 2024-10-07 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('both', 'Both')], max_length=20)),
                ('marks_credits', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('pattern', models.CharField(max_length=50)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursemaster')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusMaster',
            fields=[
                ('syllabus_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=255)),
                ('points_sub_points', models.TextField()),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursemaster')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subjectmaster')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
