# Generated by Django 5.1 on 2024-09-28 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursemaster_submitted_by_and_more'),
        ('subject', '0002_subjectmaster_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusmaster',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursemaster'),
        ),
    ]
