# Generated by Django 5.1 on 2024-09-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_syllabusmaster_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmaster',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
