# Generated by Django 5.1 on 2024-09-30 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursemaster_submitted_by_and_more'),
        ('subject', '0004_subjectmaster_semester_subjectmaster_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmaster',
            name='course_id',
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursemaster'),
        ),
    ]
