# Generated by Django 5.1 on 2024-09-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_rename_course_subjectmaster_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusmaster',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
