# Generated by Django 5.1 on 2024-10-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('staff', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemaster')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subjectmaster')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffmaster')),
            ],
        ),
    ]
