# Generated by Django 5.1 on 2024-09-21 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '__first__'),
        ('fees', '__first__'),
        ('student', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('fees_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees_unpaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_apply', models.DateField()),
                ('admission_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemaster')),
                ('fees_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feesstructure')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmaster')),
            ],
        ),
    ]
