# Generated by Django 5.1 on 2024-09-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_remove_coursemaster_division_and_more'),
        ('staff', '0003_alter_staffleave_approved_by'),
        ('student', '0004_studentleave_student_approved_by'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('questions', models.JSONField(default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemaster')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffmaster')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subjectmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=5)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exampaper')),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmaster')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subjectmaster')),
            ],
        ),
    ]
