# Generated by Django 5.1 on 2024-10-07 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('student', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesStructure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cast', models.CharField(max_length=50)),
                ('is_scholarship', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.CharField(max_length=10)),
                ('status', models.CharField(default='active', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_gap', models.CharField(max_length=20)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemaster')),
            ],
        ),
        migrations.CreateModel(
            name='FeesMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=50)),
                ('upload_document', models.ImageField(blank=True, null=True, upload_to='fees_documents/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemaster')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmaster')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fees_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feesstructure')),
            ],
        ),
    ]
