# Generated by Django 5.1 on 2024-09-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesmaster',
            old_name='course',
            new_name='course_id',
        ),
    ]
