# Generated by Django 5.1 on 2024-09-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_rename_course_feesmaster_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesmaster',
            old_name='course_id',
            new_name='course',
        ),
    ]
