# Generated by Django 5.1 on 2024-09-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Approved', 'Approved'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
