# Generated by Django 5.1 on 2024-10-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_studentmaster_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
