# Generated by Django 5.1 on 2024-10-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursemaster_submitted_by_and_more'),
        ('student', '0007_studentattendance_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursemaster'),
        ),
    ]
