# Generated by Django 5.1 on 2024-10-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentattendance_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='course',
            new_name='course_id',
        ),
    ]
