# Generated by Django 5.1 on 2024-10-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_rename_course_studentattendance_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='course_id',
            new_name='course',
        ),
    ]
