# Generated by Django 5.1 on 2024-09-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='school_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('school_documents', models.ManyToManyField(blank=True, to='scholarship.document')),
            ],
        ),
    ]
